sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3308
    database: sky_take_out
    username: root
    password: "123456"
#TODO alioss需要完善
# alioss:
#   endpoint:
#   access-key-id:
#   access-key-secret:
#   bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0   #默认0号数据库
  wechat:
    appid: wxf647266814baa6c8
    secret: f16dc5a00614a521e2fb60fd613efde2
#  shop:
#    address: xxx
#  baidu:
#      ak: xxx,需要自己去百度地图开放平台获取ak