sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3308
    database: sky_take_out
    username: root
    password: "123456"
#TODO alioss需要完善
# alioss:
#   endpoint:
#   access-key-id:
#   access-key-secret:
#   bucket-name:
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0   #默认0号数据库